### ISSUE TITLE
Using React4s component in Javascript

### ISSUE THREAD

**Issue by Poorva17** [Ahnfelt/react4s#10]
Hi,

[This example](http://www.react4s.org/examples/react-js) shows how to use js components in React4s. I would like to know other way of interoperability.

**Comment by Ahnfelt** [comment]
You can do this:

```scala
ReactBridge.componentToReact(Component(MyComponent))
```

The returned value can be used directly as a raw React.js component.

Or if you're using a configured bridge, such as NpmReactBridge from @Taig's library:
```scala
NpmReactBridge.componentToReact(Component(MyComponent))
```

**Comment by Poorva17** [comment]
Hi @Ahnfelt ,

I exported 
`@JSExportTopLevel("MyComponent")
@JSExportAll
object MyComponent {
  val SomeComponent: ReactBridge.ReactElement = NpmReactBridge.componentToReact(Component(React4sComponent))
}
`
published to npm registry. 

I want to use this in React.js project. 
I have included this published npm module in package.json

Can you explain usage of this in React.js project.?

Note - including ` <module.MyComponent.SomeComponent/>` in render method of any other component is giving following error
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.` 

Is there any example which I can refer?
