### ISSUE TITLE
Interoperability - use a component that was defined in plain JavaScript+React.

### ISSUE THREAD

**Issue by Poorva17** [Ahnfelt/react4s#13]
Hello @Ahnfelt ,

I was referring to [documentation for interoperability](http://www.react4s.org/examples/react-js) and I am unable to use it.

Is there any working example which I can refer?

**Comment by atooni** [comment]
Hi Poorva, 
we are currently developing our own Management UI with react4s. So far we have (re)written our compnents into Scala. 
This having said, we will require the same feature as well. It would be very helpful if you could provide an error message or a link to the repo that is having the issue ? - Personally I would guess you are missing a npm dependency in your build file or are using a wrong JSImport ?

My 2cts
Andreas

**Comment by Poorva17** [comment]
Hi @atooni, 

I tried two ways for reusing,

1. Include js file in script tag of index.html where I hit error `target container is not DOM element`
2. Create npm module with js file and then use @JSImport but that way I am unable to use component.

Example shown in [documentation](http://www.react4s.org/examples/react-js) does not give adequate information about using interoperability feature.

**Comment by atooni** [comment]
Hi Poorva, 
I am afraid, for me the information is not enough to give you any more hints. The error might be in your build.sbt or in the code itself. If you can't link to your project itself, it would be very helpful if you created a minimal demo on github showing the error. 
Actually trying things out in a sandbox before adding them to the "real" app works very well for me and we have created a sample app for ourselves for this reason. Sometimes it is easier to understand a certain concept in isolation before translating it into the app.

**Comment by Poorva17** [comment]
Hi @atooni ,
Sorry for inadequate information. 
Here are details -
 
This is how build.sbt looks for adding npm dependency
```scala
 npmDependencies in Compile ++= Seq(
      "react" -> "16.4.1",
      "react-dom" -> "16.4.1",
      "@material-ui/core" -> "1.4.1"
    )
```

JsImport code is as follows - 
```scala
@js.native
@JSImport("@material-ui/core/Button", JSImport.Default)
object Button extends js.Object
```
Now we are not quite sure how to use this in react4s component.

**Comment by atooni** [comment]
Ho Poorva, 

like I have said, I haven't used JS based react Components myself, but from what I see I think your implementation is most likely not ok. Please consider the rest of the answer to theoretical as I haven't practically tested it. 

From the documentation you are referring to, it must be something like 
object FancyButton extends JsComponent(js.Dynamic.global.FancyButton). 

Assuming your library would expose "Button" it should be similar to 
object Button extends JsComponent(js.Dynamic.global.Button). 
The key point **AFAIK** is to wrap it in a JSComponent.

Then you could use it like 

Button(
  // whatever config does into a Material ui button ....
)

If that doesn't help, I do hope that @Ahnfelt can come to the rescue :)

Andreas

**Comment by Poorva17** [comment]
Thank you @atooni for help.

Interoperability worked with following changes :) ,

build.sbt for npm dependencies -
```scala
npmDependencies in Compile ++= Seq(
      "react" -> "16.4.1",
      "react-dom" -> "16.4.1",
      "@material-ui/core" -> "1.4.1"
    )
```

JsImport looks like this -
```scala
@js.native
@JSImport("@material-ui/core", JSImport.Namespace)
object Material extends js.Object {
  val Button: js.Dynamic = js.native
}

object Button extends JsComponent(Material.Button)

```

Usage in React4s Componets - 
```scala
    val component = E.div(
       Button(J("color", "secondary"), Text("Click"))
    )
```
@Ahnfelt you can close this issue

**Comment by Ahnfelt** [comment]
👍

**Comment by atooni** [comment]
Poorva, 

thanks for sharing the update, I was just about to try it for myself.

**Comment by atooni** [comment]
Hi all, 

for what it's worth, I have hacked a crude generator together to get the plain wrappers for all Material Components, so for it seems to work nicely. 

https://github.com/woq-blended/blended.mgmt.ui, there is a rudimentary example to use the appbar within the SampleApp. 

Best regards
Andreas
