### ISSUE TITLE
Support for react context api

### ISSUE THREAD

**Issue by Poorva17** [Ahnfelt/react4s#16]
We have react component say **ExampleComponent** which internally uses [react context api](https://reactjs.org/docs/context.html) - precisely it uses 
`const { Provider, Consumer } = React.createContext(defaultState)`. We are interested in making this **ExampleComponent** interoperable so that it can be used from react4s application. Is there any way or support in react4s for this usecase.

**Comment by Ahnfelt** [comment]
I've released a new version of React4s that has support for contexts:

http://www.react4s.org/examples/contexts

Does this fit your usecase?

**Comment by Poorva17** [comment]
Thanks @Ahnfelt for adding support for react context. 👍
