### ISSUE TITLE
Order of components important when adding multiple instances of same component

### ISSUE THREAD

**Issue by abrighton** [Ahnfelt/react4s#18]
I have a React4s component with a unique props value. Now if I receive an event and the render method inserts a second component of the same type with a different props value before the first one, the original instance of the component gets configured with the new property. If I append the new component instead of inserting it, it gets configured with the new value as expected. Maybe this is the expected behavior, but it is a bit confusing that the order of components is so important.

This was causing problems, since the component displays a chart and needs to keep track of the JS chart object in some local state or var and gets confused when it is configured with properties that don't match that existing state.

What is the recommended way to deal with multiple instances of a component that need to manage internal state? I suppose one solution in this case would be to "emit" the chart value and have it passed in again as a property the next time it is rendered.

**Comment by Ahnfelt** [comment]
In React, the way to deal with internal state in the face of insertion, deletion and reordering of components is to use keys: https://reactjs.org/docs/lists-and-keys.html

In React4s, keys are added with the `.withKey("mykey")` method, eg.:

```scala
Tags(for(item <- items) yield Component(MyComponent, item).withKey(item.id)).
```

**Comment by abrighton** [comment]
Thanks. That fixes the problem.
