### ISSUE TITLE
Higher order components using react4s

### ISSUE THREAD

**Issue by Poorva17** [Ahnfelt/react4s#22]
Hello @Ahnfelt ,

We have usecase where we use higher order components. 
```javascript

const WithAddtionalProps = Component => {
  return props => {
    return <Component {...props} addtionalProp={some-value} />
  }
}

export default WithAddtionalProps


```
We want to write similar component using React4s. Is there any example for this use case to refer.

**Comment by Ahnfelt** [comment]
The above is really just a higher order function, eg.

```scala
def withAddtionalProps(component : (SomeProps, SomeValue) => Tag)(props : SomeProps) =
   component(props, someValue)
```

But I suspect you need more than that - if so, please elaborate.

As for higher order components, here's quote from the [React.js documentation](https://reactjs.org/docs/hooks-intro.html):

> React doesn’t offer a way to “attach” reusable behavior to a component (for example, connecting it to a store). If you’ve worked with React for a while, you may be familiar with patterns like render props and higher-order components that try to solve this. But these patterns require you to restructure your components when you use them, which can be cumbersome and make code harder to follow. If you look at a typical React application in React DevTools, you will likely find a “wrapper hell” of components surrounded by layers of providers, consumers, higher-order components, render props, and other abstractions. While we could filter them out in DevTools, this points to a deeper underlying problem: React needs a better primitive for sharing stateful logic.

This is essentially the reason why there's no example of higher order components in the React4s documentation - Attachables (which are similar to Hooks, but predates them) are a better solution to most of the problems that higher order components solve.

**Comment by Poorva17** [comment]
Thanks @Ahnfelt. Our use case was related to react context where component gets some additional props using context.consumer. But this helps. Thanks
