### ISSUE TITLE
Hardcoded paths in sourcemaps?

### ISSUE THREAD

**Issue by klntsky** [Ahnfelt/react4s#23]
Strangely enough, I get this network error when trying to use sourcemaps in Firefox:

```
Error while fetching an original source: TypeError: NetworkError when attempting to fetch resource.
Source URL: file:///C:/Users/Joakim/Documents/GitHub/react4s/src/main/scala/com/github/ahnfelt/react4s/ReactBridge.scala[Learn More]
```

Both `*-fastopt.js.map` and `*-opt.js.map` contain references to absolute paths like that one above, which is not even valid on my OS.

**Comment by Ahnfelt** [comment]
Hi and thank you for using React4s.

Apparently that's the default behavior. I've added the following to build.sbt in v0.9.26:

```scala
scalaJSLinkerConfig := {
    val fastOptJSURI = (artifactPath in (Compile, fastOptJS)).value.toURI
    scalaJSLinkerConfig.value.withRelativizeSourceMapBase(Some(fastOptJSURI))
}
```

From: https://github.com/scala-js/scala-js/issues/3135

I'm not sure where to find the documentation on the above - does it fix the problem on your end?
