### ISSUE TITLE
Support scala-2.13

### ISSUE THREAD

**Issue by abrighton** [Ahnfelt/react4s#25]
I needed to upgrade a project to scala-2.13, but noticed that then the react4s (and router4s) dependency is not found. Any plans to support the new Scala version?

**Comment by Ahnfelt** [comment]
Absolutely.

I was waiting for a Scala.js release for 2.13, but maybe I [missed it](https://github.com/scala-js/scala-js/releases/tag/v0.6.28-scala-2.13.0)? The Scala.js site is down right now, but if there is indeed a stable release, I'll start working on releasing 2.13 version of React4s.

**Comment by Ahnfelt** [comment]
I have now released a new version with Scala 2.13 support: React4s 0.9.27

**Comment by abrighton** [comment]
Thanks for the quick response!
