### ISSUE TITLE
Lift 3rd party react components

### ISSUE THREAD

**Issue by Taig** [Ahnfelt/react4s#3]
I played around with the library a bit but could not find a way to integrate with existing react components. It would be nice if we could do something in the fashion of

```scala
case class MuiRasedButton( label: P[String], disabled: P[Boolean] )
  extends ExternalComponent( Mui.RaisedButton, "label" -> label, "disabled" -> disabled )
```

which would then enable me to use the component in the react4s DSL.

I'm a total beginner with react as well as ScalaJS, but would be happy to work on a PR if you gave me a bit of a direction.

**Comment by Ahnfelt** [comment]
Absolutely :) I'll take a look at it tonight.

**Comment by Ahnfelt** [comment]
Hi Niklas, I've gone ahead and implemented a simple version of it. DynamicComponent: efd0f314c3d0dc2d8435e18a5c8a0157ee6a84e3

Does this enable your use case?

**Comment by Ahnfelt** [comment]
Actually, it'd be pretty nice if you could implement your ExternalComponent proposal instead - it'd be much nicer to actually use the component.

I've created a Gitter, maybe we can discuss it there? https://gitter.im/react4s/Lobby

**Comment by Taig** [comment]
Couldn't you pretty much use your implementation already in that way if it wasn't final?

I just joined your Gitter and am happy to continue the discussion there.
