### ISSUE TITLE
Publish tags 

### ISSUE THREAD

**Issue by atooni** [Ahnfelt/react4s#7]
Hello, 

your library looks very interesting. Could you perhaps also push your tags to github and the public repositories ? 

Best regards and thanks for the library 
Andreas

**Comment by Ahnfelt** [comment]
Hi @atooni, thank you for your interest. I haven't used git tags for versioning React4s thus far, but I don't mind adding them going forward, starting with the current version. Would that suffice?

**Comment by atooni** [comment]
@Ahnfelt : That would be perfectly fine. For now I have cloned the project to give it a spin. In a couple of hours I was able to transform our boilerplate project from another react library to yours. 

So far it looks very clean and I do like it much more. On another note, I have added some version bumps to my clone, I will create a PR; perhaps you would like to adopt those.

Best regards 
Andreas

**Comment by Ahnfelt** [comment]
@atooni I've added a tag (v0.9.7) to the current version and intend to tag future versions.

I'm glad you like it 👍 If you have questions, you can find me on https://gitter.im/scala-js/scala-js (@Ahnfelt).

**Comment by atooni** [comment]
@Ahnfelt : Thank you very much this will help a lot maintaining the code base. Will those releases also be on one of the public repos ?

**Comment by Ahnfelt** [comment]
Ah, absolutely, just as they are now. I'm currently releasing as SNAPSHOT versions for 0.y.z. Soon React4s will reach 1.0.0, and before that I'll look into releasing non-SNAPSHOT versions.
